In [1]:
!pip install -U -f https://www.open3d.org/docs/latest/getting_started.html open3d

Looking in links: https://www.open3d.org/docs/latest/getting_started.html
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 400.3/400.3 MB 3.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.2/10.2 MB 28.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 139.4/139.4 kB 19.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 55.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 56.3 MB/s eta 0:00:00
  Attempting uninstall: widgetsnbextension
    Found existing installation: widgetsnbextension 3.6.6
    Uninstalling widgetsnbextension-3.6.6:
      Successfully uninstalled widgetsnbextension-3.6.6
  Attempting uninstall: ipywidgets
    Found existing installation: ipywidgets 7.7.1
    Uninstalling ipywidgets-7.7.1:
      Successfully uninstalled ipywidgets-7.7.1


In [ ]:
import open3d
import numpy as np

pcd = open3d.io.read_point_cloud('./8th_scan_angel.ply')
pcd.estimate_normals(search_param=open3d.geometry.KDTreeSearchParamHybrid(radius=0.1, max_nn=30))

with open3d.utility.VerbosityContextManager(open3d.utility.VerbosityLevel.Debug) as cm:
    mesh, densities = open3d.geometry.TriangleMesh.create_from_point_cloud_poisson(pcd, depth=9)
    open3d.io.write_triangle_mesh('./angel.obj', mesh, write_ascii=False, compressed=False, write_vertex_normals=True, write_vertex_colors=True, write_triangle_uvs=True, print_progress=False)


PointCloud with 2338260 points.
[[ 9.73520279e+00 -1.08487282e+01  1.12793251e+02]
 [ 9.78782463e+00 -1.08750324e+01  1.12567993e+02]
 [ 9.88999748e+00 -1.09287004e+01  1.12339256e+02]
 ...
 [ 2.38477173e+01  1.28582811e+01  3.59260529e-01]
 [ 2.40419426e+01  1.29535913e+01  2.06218079e-01]
 [ 2.41655121e+01  1.30128689e+01  3.09563857e-02]]
[Open3D DEBUG] Input Points / Samples: 2338260 / 743441
[Open3D DEBUG] #   Got kernel density: 0.36980295181274414 (s), 3771.69140625 (MB) / 3923.25 (MB) / 4071 (MB)
[Open3D DEBUG] #     Got normal field: 2.0119900703430176 (s), 3771.69140625 (MB) / 3923.25 (MB) / 4071 (MB)
[Open3D DEBUG] Point weight / Estimated Area: 1.201596e-06 / 2.809643e+00
[Open3D DEBUG] #       Finalized tree: 1.3666460514068604 (s), 3845.6796875 (MB) / 3923.25 (MB) / 4071 (MB)
[Open3D DEBUG] #  Set FEM constraints: 6.1247169971466064 (s), 3771.69140625 (MB) / 3923.25 (MB) / 4071 (MB)
[Open3D DEBUG] #Set point constraints: 0.8185009956359863 (s), 3771.69140625 (MB) / 3923.2

AttributeError: 'open3d.cuda.pybind.geometry.TriangleMesh' object has no attribute 'faces'

In [2]:
!git clone https://github.com/threedle/3DHighlighter.git


Cloning into '3DHighlighter'...
remote: Enumerating objects: 192, done.
remote: Counting objects: 100% (192/192), done.
remote: Compressing objects: 100% (155/155), done.
remote: Total 192 (delta 66), reused 138 (delta 31), pack-reused 0
Receiving objects: 100% (192/192), 19.99 MiB | 12.11 MiB/s, done.
Resolving deltas: 100% (66/66), done.


In [3]:
!pip install --upgrade pip
!pip install torch==1.12.1 torchvision==0.13.1 torchaudio==0.12.1
!pip install matplotlib==3.5.2
!pip install git+https://github.com/openai/CLIP.git
!pip install kaolin==0.15.0 -f https://nvidia-kaolin.s3.us-east-2.amazonaws.com/torch-1.12.1_cu113.html

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 14.3 MB/s eta 0:00:00
  Attempting uninstall: pip
    Found existing installation: pip 23.1.2
    Uninstalling pip-23.1.2:
      Successfully uninstalled pip-23.1.2
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 776.3/776.3 MB 2.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.1/19.1 MB 79.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.7/3.7 MB 94.3 MB/s eta 0:00:00
  Attempting uninstall: torch
    Found existing installation: torch 2.1.0+cu121
    Uninstalling torch-2.1.0+cu121:
      Successfully uninstalled torch-2.1.0+cu121
  Attempting uninstall: torchvision
    Found existing installation: torchvision 0.16.0+cu121
    Uninstalling torchvision-0.16.0+cu121:
      Successfully uninstalled torchvision-0.16.0+cu121
  Attempting uninstall: torchaudio
    Found existing installation: torchaudio 2.1.0+cu121
    Uninstalling torchaudio-2.1.0+cu121:
      Successfully uninstalled torchaudio-2.1

  Cloning https://github.com/openai/CLIP.git to /tmp/pip-req-build-cskcbh35
  Running command git clone --filter=blob:none --quiet https://github.com/openai/CLIP.git /tmp/pip-req-build-cskcbh35
  Resolved https://github.com/openai/CLIP.git to commit a1d071733d7111c9c014f024669f959182114e33
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.4/53.4 kB 2.1 MB/s eta 0:00:00
  Created wheel for clip: filename=clip-1.0-py3-none-any.whl size=1369497 sha256=1bd4db780e407bc134f8ebf13e8c6920d87164a45be28406d7ddb96bf3d66699
  Stored in directory: /tmp/pip-ephem-wheel-cache-1yg0w4df/wheels/da/2b/4c/d6691fa9597aac8bb85d2ac13b112deb897d5b50f5ad9a37e4
Successfully built clip
Looking in links: https://nvidia-kaolin.s3.us-east-2.amazonaws.com/torch-1.12.1_cu113.html
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.7/4.7 MB 9.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 255.7/255.7 kB 6.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

In [ ]:

from main import optimize # Import the function from the module

class ArgsNamespace:
    def __init__(self, args_dict):
        self.__dict__.update(args_dict)

# Create an instance of ArgsNamespace



# specify the directory you want to iterate over
directory = './dataset/'  # current directory

# iterate over files in the directory

for filename in os.listdir(directory):
    object_name = filename.split('.')[0]
    print(object_name)
    print(filename)
    args = ArgsNamespace({
        'seed': 0,
        'obj_path': directory + filename,
        'output_dir': '/content/results_' + object_name,
        'object': [object_name],
        'classes': ['shoes'],
        'background': [1., 1., 1.],
        'n_views': 5,
        'frontview_std': 4,
        'frontview_center': [0., 0.],
        'show': False,
        'n_augs': 1,
        'clipavg': 'view',
        'render_res': 224,
        'clipmodel': 'ViT-L/14',
        'jit': False,
        'depth': 4,
        'width': 256,
        'n_classes': 2,
        'positional_encoding': False,
        'sigma': 5.0,
        'learning_rate': 0.0001,
        'n_iter': 2500
    })

    optimize(args)

"""
args = ArgsNamespace({
    'seed': 0,
    'obj_path': '/content/3DHighlighter/data/candle.obj',
    'output_dir': '/content/results_check2',
    'object': ['candle'],
    'classes': ['back'],
    'background': [1., 1., 1.],
    'n_views': 5,
    'frontview_std': 4,
    'frontview_center': [0., 0.],
    'show': False,
    'n_augs': 1,
    'clipavg': 'view',
    'render_res': 224,
    'clipmodel': 'ViT-L/14',
    'jit': False,
    'depth': 4,
    'width': 256,
    'n_classes': 2,
    'positional_encoding': False,
    'sigma': 5.0,
    'learning_rate': 0.00001,
    'n_iter': 500
})

optimize(args)
"""


angel
angel.obj


100%|███████████████████████████████████████| 890M/890M [00:15<00:00, 59.7MiB/s]


ModuleList(
  (0): FourierFeatureTransform()
  (1): Linear(in_features=515, out_features=256, bias=True)
  (2): ReLU()
  (3): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
  (4): Linear(in_features=256, out_features=256, bias=True)
  (5): ReLU()
  (6): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
  (7): Linear(in_features=256, out_features=256, bias=True)
  (8): ReLU()
  (9): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
  (10): Linear(in_features=256, out_features=256, bias=True)
  (11): ReLU()
  (12): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
  (13): Linear(in_features=256, out_features=256, bias=True)
  (14): ReLU()
  (15): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
  (16): Linear(in_features=256, out_features=2, bias=True)
  (17): Softmax(dim=1)
)


  0%|          | 0/2500 [00:05<?, ?it/s]


RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 14.75 GiB total capacity; 13.71 GiB already allocated; 15.06 MiB free; 13.84 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

In [ ]:

from google.colab import files

!zip -r /content/results_bowtie.zip /content/results_bowtie
files.download('/content/results_bowtie.zip')

  adding: content/results_bowtie/ (stored 0%)
  adding: content/results_bowtie/training_info.txt (deflated 87%)
  adding: content/results_bowtie/commandline_args.txt (deflated 48%)
  adding: content/results_bowtie/renders/ (stored 0%)
  adding: content/results_bowtie/renders/iter_2200.jpg (deflated 34%)
  adding: content/results_bowtie/renders/iter_1600.jpg (deflated 32%)
  adding: content/results_bowtie/renders/iter_100.jpg (deflated 33%)
  adding: content/results_bowtie/renders/iter_1100.jpg (deflated 31%)
  adding: content/results_bowtie/renders/iter_500.jpg (deflated 30%)
  adding: content/results_bowtie/renders/iter_1800.jpg (deflated 31%)
  adding: content/results_bowtie/renders/iter_800.jpg (deflated 33%)
  adding: content/results_bowtie/renders/iter_2300.jpg (deflated 38%)
  adding: content/results_bowtie/renders/iter_1700.jpg (deflated 33%)
  adding: content/results_bowtie/renders/iter_300.jpg (deflated 31%)
  adding: content/results_bowtie/renders/iter_0.jpg (deflated 34%)
  

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>